; AutoFarm config
; 这个配置文件请按你自己的热键来修改

[Hotkeys]
; Toggle 采集
ToggleGather=F10
; Toggle 刷毒塔
ToggleFarm=F9
; Toggle 刷牛筋BeefTendon
ToggleBeef=F8
; Toggle 刷独山玉
ToggleJade=F7

[Keys]
; 飒踏流星
MeteorFlight=Space
; 千斤坠   
MightyDrop=q
; 神龙吐火 注意修改一下热键为你自己的神龙吐火热键
DragonsBreath=x
; 这是治疗技能，我用的千时余响所以是~键
; 这是个特殊键(sc029), 改成别的技能热键可以直接用键盘上的键名比如q  
Heal=sc029
; 灵虚一指
TouchOfDeath=f
; 拾取 默认也是f
Loot=f
; 陌刀特殊技也是~键, 这是用来采集独山玉的
MoSpecial=sc029
; 独山玉采集间隔，默认300秒，加上陌刀特殊技和人物归位的时间，就会刚好超过5分钟多人世界的刷新时间。
JadeInterval=300000

[Timing]
; 治疗间隔， 单位是毫秒ms，1000ms=1秒，千时余响是60秒自动收伞，如果用别的治疗技能可以调整成你的技能冷却
HealCooldownMs=60000

[Gather]
; 采集热键，默认f
Key=f
; 采集间隔，默认10秒
IntervalMs=10000