; AutoFarm config
; 这个配置文件请按你自己的热键来修改

[Hotkeys]
; Toggle 采集
ToggleGather=F10
; Toggle 刷毒塔
ToggleFarm=F9
; Toggle 刷牛筋BeefTendon
ToggleBeef=F8
; Toggle 刷独山玉
ToggleJade=F7

[Keys]
; 飒踏流星
MeteorFlight=Space
; 千斤坠   
MightyDrop=q
; 神龙吐火 注意修改一下热键为你自己的神龙吐火热键
DragonsBreath=x
; 这是治疗技能，我用的千时余响所以是~键
; 这是个特殊键(sc029), 改成别的技能热键可以直接用键盘上的键名比如q  
Heal=sc029
; 灵虚一指
TouchOfDeath=f
; 拾取 默认也是f
Loot=f
; 陌刀特殊技也是~键, 这是用来采集独山玉的
MoSpecial=sc029
; 闪避键，用于人物归位
Dodge=LShift

[Timing]
; 按键轻点时长，单位毫秒，影响大多数技能和采集按键的按下时间
TapMs=60
; 每轮循环开始前的基础等待时间，单位毫秒
InitialDelayMs=100
; 飒踏流星按住时长，单位毫秒 (飒踏流星需要按住释放)
MeteorHoldMs=2000
; 飒踏流星释放后到千斤坠之间的等待时间，单位毫秒，这个受到延迟影响，高延迟输入太早或者太晚会出现“高度不够的情况”，默认3500应该适配大多数情况
BeforeMightyDropMs=3500
; 千斤坠后到神龙吐火之间的等待时间，单位毫秒
BeforeDragonsBreathMs=1200
; 神龙吐火释放后的收尾等待时间，单位毫秒
AfterDragonsBreathMs=2000
; 灵虚一指连续点击次数，用于刷牛筋循环
TouchOfDeathCount=10
; 千斤坠后到开始连续释放灵虚一指之间的等待时间，单位毫秒
BeforeTouchOfDeathMs=300
; 每次灵虚一指之间的间隔时间，单位毫秒
BetweenTouchOfDeathMs=100
; 灵虚一指整轮结束后的等待时间，单位毫秒
AfterTouchOfDeathMs=1800
; 拾取后额外等待时间，单位毫秒
AfterLootMs=500
; 治疗技能冷却前的额外等待时间，单位毫秒
HealPreDelayMs=1100
; 治疗技能释放后的额外等待时间，单位毫秒
HealPostDelayMs=1000
; 治疗间隔， 单位是毫秒ms，1000ms=1秒，千时余响是60秒自动收伞，如果用别的治疗技能可以调整成你的技能冷却
HealCooldownMs=60000
; 独山玉循环开始前的短暂等待时间，单位毫秒
JadeStartDelayMs=100
; 陌刀特殊技释放后到闪避归位前的等待时间，单位毫秒
AfterMoSpecialMs=4000
; 独山玉下一轮采集间隔，默认300秒；加上陌刀特殊技和人物归位时间后，刚好略超过多人世界刷新时间
JadeIntervalMs=300000

[Gather]
; 采集热键，默认f
Key=f
; 采集间隔，默认10秒
IntervalMs=10000
